name: 'Jmeter- $(Date:yyyyMMdd).$(Rev:r)'
variables:
  - group: Jmeter
  
trigger: none 
pr: none 
stages:
  - stage: Jmeter
    jobs:
    - job: Siebel_Jmeter
      displayName: 'SiebelJmeter'
      pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL02
      steps: 
        - task: CmdLine@2
          displayName: 'JmeterMemberInfo Test'
          name: 'JmeterBatchscript'
          inputs:
            script: |
              C:\apache-jmeter-5.4.1\bin\jmeter -Jjmeter.save.saveservice.output_format=csv -Jjmeter.reportgenerator.apdex_satisfied_threshold=1500 -n -t C:\apache-jmeter-5.4.1\bin\MemberInfo.jmx -l C:\results\MemberInfo.jtl -e -o C:\results\MemberInfo