name: 'Jmeter- $(Date:yyyyMMdd).$(Rev:r)'
  
trigger: none 
pr: none 

stages:
  - stage: Jmeter
    jobs:
    - job: Siebel_Jmeter
      displayName: 'Siebel_Jmeter'
      pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL02 
      steps: 
      - task: CopyFiles@2 
        inputs: 
          SourceFolder: '$(SourceDir)'
          Contents: '**'
          TargetFolder: '$(TargetDir)'
          CleanTargetFolder: true
        - task: Jmeter@2
          displayName: 'JmeterMemberInfo'
          name: "MemberInfo"
          inputs:
             targetType: 'filePath'
             workingDirectory: $(TargetDir)
             filePath: 'C:/apache-jmeter-5.4.1/bin/MemberInfo.jmx'
        - task: BatchScript@1
          displayName: 'JmeterMemberInfo'
          name: 'MemberInfo'
          inputs:
             workingFolder: $(TargetDir)
             filename: 'C:/apache-jmeter-5.4.1/MemberInfo.bat'
    