name: 'Jmeter- $(Date:yyyyMMdd).$(Rev:r)'
  
trigger: none 
pr: none 
stages:
  - stage: Jmeter
    jobs:
    - job: Siebel_Jmeter
      displayName: 'SiebelJmeter'
      pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL01
        steps: 
         - task: BatchScript@1
           displayName: 'JmeterMemberInfo Test'
           name: 'MemberInfoJmeter'
           inputs:
            filename: 'C:\apache-jmeter-5.4.1\MemberInfo.bat'