name: 'Jmeter- $(Date:yyyyMMdd).$(Rev:r)'
  
trigger: none 
pr: none 
stages:
  - stage: Jmeter
    jobs:
    - job: Siebel_Jmeter
      displayName: 'Siebel_Jmeter'
      pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL02
        steps:
     - task: BatchScript@1
  inputs:
    filename: 'C:\apache-jmeter-5.4.1\MemberInfo.bat'