# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: Jmeter
    jobs:
    - job: Siebel_MemberInfo
      displayName: 'MemberInfo'
      pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL02 
      steps: 
      - task: CopyFiles@2 
        inputs: 
          SourceFolder: '$(SourceDir)'
          Contents: '**'
          TargetFolder: '$(TargetDir)'
          CleanTargetFolder: true
      - task: Jmeter@2
        displayName: 'JmeterMemberInfo'
        name: "MemberInfo"
        inputs:
             targetType: 'filePath'
             workingDirectory: $(TargetDir)
             filePath: '$(TargetDir)/apache-jmeter-5.4.1/bin/MemberInfo.jmx'
      - task: BatchScript@1
        displayName: 'JmeterMemberInfo'
        name: 'MemberInfo'
        inputs:
             workingFolder: $(TargetDir)
             filename: '$(TargetDir)/apache-jmeter-5.4.1/MemberInfo.bat'
