name: 'Jmeter- $(Date:yyyyMMdd).$(Rev:r)'
variables:
  - group: Jmeter
  
trigger: none 
pr: none 
stages:
  - stage: Jmeter
    jobs:
    - job: Siebel_Jmeter
      displayName: 'SiebelJmeter'
      pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL02
      steps: 
         - task: BatchScript@1
           displayName: 'JmeterMemberInfo Test'
           name: 'JmeterBatchscript'
           inputs:
             filename: '$(devjmeter)/MemberInfo.bat'
             modifyEnvironment: true
             failOnStandardError: true
