name: 'Jmeter- $(Date:yyyyMMdd).$(Rev:r)'
variables:
  - group: Jmeter
  
trigger: none 
pr: none 
stages:
  - stage: Jmeter
    jobs:
    - job: Siebel_Jmeter
      displayName: 'SiebelJmeter'
      pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL02
      steps: 
        - task: CmdLine@2
          displayName: 'JmeterMemberInfo Test'
          name: 'JmeterBatchscript'
          inputs:
            script: |
              '$(devjmeter)/bin/jmeter -n -t '$(devjmeter)/bin/MemberInfo.jmx -l $(results)/MemberInfo.jtl -e -o $(results)/MemberInfo
                    pause