name: 'Jmeter- $(Date:yyyyMMdd).$(Rev:r)'
  
trigger: none 
pr: none 

pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL02
- task: BatchScript@1
  inputs:
    filename: 'C:\apache-jmeter-5.4.1\MemberInfo.bat'