name: 'Jmeter- $(Date:yyyyMMdd).$(Rev:r)'
  
trigger: none 
pr: none 
stages:
  - stage: Jmeter
    jobs:
    - job: Siebel_Jmeter
      displayName: 'Siebel_Jmeter'
      pool:
        name: 'Siebel'
        demands:
        - agent.name -equals SEADVSBL19APL02
- task: JMeterInstaller@0
  inputs:
    jmeterVersion: '5.4.2'
    - task: CmdLine@2
  inputs:
    script: 'C:\apache-jmeter-5.4.1\bin\jmeter -n -t C:\apache-jmeter-5.4.1\bin\MemberInfoQA.jmx -l C:\results\MemberInfo.jtl -e -o C:\results\MemberInfo'